DROP SCHEMA IF EXISTS boarding CASCADE;
DROP SCHEMA IF EXISTS commercial CASCADE;
DROP SCHEMA IF EXISTS loyalty CASCADE;
DROP SCHEMA IF EXISTS airline CASCADE;
DROP SCHEMA IF EXISTS security CASCADE;
DROP SCHEMA IF EXISTS identity CASCADE;
DROP SCHEMA IF EXISTS geography CASCADE;